version: 0.2

phases:
  pre_build:
    commands:
      - echo "Checking for create-vpc.yml"
      - pwd
      - ls -al
      - find . -name 'create-vpc.yml'
  build:
    commands:
      - echo "Uploading to S3"
      - aws s3 cp create-vpc.yml s3://cf-templates-z5q3ztki8ohd-us-west-2/
