version: 0.2

phases:
  pre_build:
    commands:
      - echo "Checking if file exists"
      - ls -al
  build:
    commands:
      - echo "Uploading create-vpc.yml to S3"
      - aws s3 cp create-vpc.yml s3://tulipsitc/
